# This file configures the analyzer, which statically analyzes Dart code to
# check for errors, warnings, and lints.
#
# The issues identified by the analyzer are surfaced in the UI of Dart-enabled
# IDEs (https://dart.dev/tools#ides-and-editors). The analyzer can also be
# invoked from the command line by running `flutter analyze`.

# The following line activates a set of recommended lints for Flutter apps,
# packages, and plugins designed to encourage good coding practices.
include: package:flutter_lints/flutter.yaml

linter:
  rules:
    avoid_print: false  
    prefer_single_quotes: true
    avoid_relative_lib_imports: true
    cancel_subscriptions: true
    close_sinks: true
    cascade_invocations: true
    unnecessary_overrides: true
    unnecessary_await_in_return: true
    avoid_void_async: true
    always_declare_return_types: true
    avoid_annotating_with_dynamic: true
    avoid_function_literals_in_foreach_calls: true
    file_names: true
    flutter_style_todos: true
    library_prefixes: true
    prefer_null_aware_method_calls: true
    recursive_getters: true
    require_trailing_commas: true
    unawaited_futures: true
    unnecessary_late: true
    use_string_buffers: true
    use_super_parameters: true
    sized_box_for_whitespace: true
    sized_box_shrink_expand: true
    cast_nullable_to_non_nullable: true

